### ISSUE TITLE
PeP-Spende Betrag in Ziffern

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/latex-template#1]
Es wäre gut, wenn es beim Betrag in Ziffern ein Tausendertrennzeichen gäbe.
Weiterhin sollte da auch ein ,– € hinter gesetzt werden.

Also z.B. 5.000,– €
Wenn man das einfach in die Klammer setzt, kommt es zu komischen Erscheinungen. Liegt vermutlich daran, dass er den Betrag direkt in Worte übersetzt.

**Comment by maxnoe** [comment]
Haben wir jemals nicht glatte Beträge? Wenn nein, könnte ich den Strich einfach eintragen.

**Comment by maxnoe** [comment]
Solved in 26f3327
