### ISSUE TITLE
Adressänderung in der Satzung

### ISSUE THREAD

**Issue by marschmitz** [pep-dortmund/latex-template#11]
Unter § 12 steht in der Satzung noch die Alfred Nobel Str.
Bitte korrigieren.

**Comment by maxnoe** [comment]
Ist das hier richtig?

**Comment by hmoldenhauer** [comment]
Da sollte selbstverständlich der Sitz der Gesellschaft der Freunde der Universität Dortmund e.V. stehen. Habe ich korrigiert. War auch in der notariell eingereichten Satzung so. Keine Ahnung, warum das auf der Homepage falsch war.
