### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/latex-template#2]
Wenn man einfach nur mit lualatex --interaction=nonstopmode kompiliert, zeigt der mir
[afterskip=1ex plus 0.5ex minus 0.2ex, beforeskip=-2ex
plus -0.5ex minus -0.2ex, ]section 
zwischen dem Titel und der Anrede an. Sollte glaube ich nicht so sein

**Comment by maxnoe** [comment]
Ist deine Koma-Skript Version aktuell? Klingt für mich als würde er das optionale Argument nicht verstehen.  `tlmgr update koma-script`

**Comment by hmoldenhauer** [comment]
daran lag es
