### ISSUE TITLE
wasysym doesn't find font

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/latex-template#4]
when compiling pep_mitgliedsantrag.tex Lua generates:

```
!LuaTeX error: cannot open Type 1 font file for reading (wasy10.pfb)
 ==> Fatal error occurred, no output PDF file produced!
```

I think there is a font missing...
It seems that it isn't installed with the standard TeX-files

**Comment by maxnoe** [comment]
Both the package and the font are definetly long time members of TeX Live and miktex.

See:
https://www.ctan.org/pkg/wasysym
https://www.ctan.org/pkg/wasy2

If you have not full install of TeX Live you can install those packages with tlmgr:

`tlmgr install wasy2`
`tlmgr install wasysym`

But i'll check if we need these symbols at all.
