### ISSUE TITLE
Stipendienvertrag

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/latex-template#7]
LaTeX weigert sich auf der ersten Seite die Seitenzahl so zu setzen wie auf den anderen Seiten.

**Comment by maxnoe** [comment]
Ist das stipendium_initiativ_vertrag.tex?

**Comment by hmoldenhauer** [comment]
jo

**Comment by maxnoe** [comment]
Kannste kurz sagen. was das Problem ist? Du veränderst die Headheight, dadurch wandert die ganze Seite nach unten. Also ist auch die Seitenzahl weiterunten?

**Comment by hmoldenhauer** [comment]
Ich würd gerne nur auf der ersten Seite den header haben, danach nicht mehr.
Mir ist aber keine wirklich gute Lösung dazu eingefallen (bzw. das Internet hatte keine für mich parat).

Es sieht halt irgendwie ein bisschen blöd aus, wenn auf jeder Seite wieder unser Logo zu finden ist...

**Comment by maxnoe** [comment]
Ich hab das mit geomtry und minipagen gelöst

**Comment by hmoldenhauer** [comment]
Okay, da hätte ich auch drauf kommen können.
Habe nur die ganze Zeit versucht das irgendwie mit ner titlepage zu lösen ;)
