### ISSUE TITLE
§-Zeichen vor section verschwunden

### ISSUE THREAD

**Issue by hmoldenhauer** [pep-dortmund/latex-template#9]
Durch die Ersetzung von 
 -\titleformat{\section}{\normalfont\Large\bfseries}{\S\thesection}{1em}{}
durch
+\renewcommand*{\sectionformat}{\S\thesection\autodot\enskip}

Ist das §-Zeichen vor den Überschriften nicht mehr Vorhanden.

**Comment by maxnoe** [comment]
Bei mir sind die noch da.
Was ist deine Koma-Script version?
meine ist 3.19.

**Comment by hmoldenhauer** [comment]
meine ist 3.16.
Sollte ich also wohl mal updaten...

**Comment by hmoldenhauer** [comment]
okay, nach einem update, latex zerschießen (keine Ahnung warum das passiert ist beim normalen update) und einer kompletten latex-Neuinstallation ist nun alles so, wie es soll :)
